### ISSUE TITLE
Settings Fragment overlapped

### ISSUE THREAD

**Issue by bdushi** [googlecodelabs/android-navigation#12]
When go to Settings Fragment, PopUp menu stay visible and if I click again Settings Fragment is Overlapped

**Comment by MarianVasilca** [comment]
I think you described the same issue reported in the [Google Issue Tracker](https://issuetracker.google.com/issues/79407969).

**Comment by bdushi** [comment]
We are referring to the same issue, but what I think is that the issue lies on the Overflow menu visibility.

**Comment by MarianVasilca** [comment]
It seems like the issue has been [fixed](https://issuetracker.google.com/issues/79407969#comment2) and will be available in alpha02 version.

**Comment by bdushi** [comment]
The issue has been fixed but what I see inappropriate was the menu visibility, must be visible false.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
