### ISSUE TITLE
Up navigation in deep link tab

### ISSUE THREAD

**Issue by ubuntudroid** [googlecodelabs/android-navigation#13]
When in portrait mode (so the navigation drawer is not visible, but the bottom bar is) the up button in the toolbar is shown when switching to the deep link tab via the bottom bar. As far as I know this shouldn't be the case. I would only have it visible when you're in landscape mode and the drawer is active.

I understand that this is done by the Navigation Components handling switching the tab as a simple forward navigation. However that isn't the case - as all tabs are created equal. ;) 

So might be that's not a bug in the codelab, but in the Navigation Components library? Then again, it would also have to accomodate for what happens when you then switch to landscape where the up button would suddenly become appropriate - this doesn't sound trivial.

**Comment by viperwarp** [comment]
I found a work around for navigating between top-level destinations. There doesn't seem to be anything built in to support this use case. You can reset the `NavGraph#startDestination` in code to maintain the top level behaviour when navigating to other top level destinations.
https://gist.github.com/viperwarp/fbf275830d626c24761586cef5c53a57

**Comment by ubuntudroid** [comment]
@viperwarp That actually sounds like an interesting approach 👍 , I really wish Google had an out of the box solution for this though.

**Comment by Dennis815** [comment]
I'm not seeing this issues in my app using a `BottomNavigationView`. The up button does not show in my `Toolbar` when navigating between the fragments via the bottom nav bar but tapping the system back button still takes me back to the fragment designated as the start destination from the fragments for the other tabs.

The catch is, however, this behaviour seems to have extended itself across my whole app. Navigating using actions from an item in a `RecyclerView` to a list item details fragment page does not create an up button in the toolbar. So perhaps I may have not implemented Navigation correctly...

I can't see any differences in what I've done compared to the codelab app. The only thing I can think of is that the codelab app integrates both a bottom nav bar and side nav drawer into its nav structure depending on the orientation/side of the screen. Perhaps that's the cause?

Whatever the issue is, it's one I might be happy to exploit... I have manually set up the up button in the list details fragment page but my problem now is [learning how to hook that up and pop it off the back stack](https://stackoverflow.com/questions/51115515/how-to-handle-up-button-in-toolbar-kotlin) .

Worth posting my code here do you think? Or are you/any others seeing the same thing?

**Comment by ubuntudroid** [comment]
I haven't been able to follow up on this topic during the last weeks. And although I fear that no one over at Google is actually monitoring the issues reported here I think it could still make sense to use this thread as a discussion base for possible solutions. So yes, I'm surely interested in seeing your solution. :)

**Comment by Dennis815** [comment]
Hopefully that means they are hard at work with fixes and enhancements! Well here goes anyway the relevant bits of my code.

**activity_main.xml**

    <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="0dp"
            android:layout_height="?attr/actionBarSize"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
        
        <fragment
            android:id="@+id/nav_host_fragment"
            android:name="androidx.navigation.fragment.NavHostFragment"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_gravity="fill"
            app:defaultNavHost="true"
            app:layout_constraintBottom_toTopOf="@id/bottom_nav"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/toolbar"
            app:navGraph="@navigation/nav_graph" />

        <android.support.design.widget.BottomNavigationView
            android:id="@+id/bottom_nav"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:menu="@menu/navigation" />

    </android.support.constraint.ConstraintLayout>

**MainActivity.kt**

    class MainActivity : AppCompatActivity() {

        override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)
            setContentView(R.layout.activity_main)

            val toolbar = findViewById<Toolbar>(R.id.toolbar)
            setSupportActionBar(toolbar)

            val host: NavHostFragment = supportFragmentManager
                .findFragmentById(R.id.nav_host_fragment) as NavHostFragment? ?: return

            val navController = host.navController

            setupBottomNavMenu(navController)

        override fun onOptionsItemSelected(item: MenuItem): Boolean {
            when (item.itemId) {
                R.id.menu_song_edit -> {
                    val songBundle = Bundle()
                    songBundle.putString("titleArg", song_title.text.toString())
                    NavHostFragment.findNavController(nav_host_fragment).navigate(R.id.goto_songedit, songBundle)
                    return true
                }
                else -> return NavigationUI.onNavDestinationSelected(item,
                    Navigation.findNavController(this, R.id.nav_host_fragment))
                    || super.onOptionsItemSelected(item)
            }
        }

        override fun onSupportNavigateUp(): Boolean {
            return Navigation.findNavController(this, R.id.nav_host_fragment).navigateUp()
        }

        private fun setupBottomNavMenu(navController: NavController) {
            findViewById<BottomNavigationView>(R.id.bottom_nav)?.let { bottomNavView ->
            NavigationUI.setupWithNavController(bottomNavView, navController)
            }
        }

    }

**MainFragment.kt**

The other fragment.kt files are basically the same.

```
class MainFragment : Fragment() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        setHasOptionsMenu(true)
        return inflater.inflate(R.layout.fragment_main_layout, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
    }

    override fun onCreateOptionsMenu(menu: Menu?, inflater: MenuInflater?) {
        //super.onCreateOptionsMenu(menu, inflater)
        inflater?.inflate(R.menu.toolbar_main, menu)
        (activity as AppCompatActivity).supportActionBar?.setTitle(R.string.app_name)
    }
```

The nav_graph.xml is standard. Nothing different there.

**Comment by ubuntudroid** [comment]
@Dennis815 Sorry for getting back so late to you.

I think you are missing one thing in your code: wiring up your toolbar with the NavController (I just assume you are using a toolbar). For that you would need to call `toolbar.setupWithNavController(navController)` (if you are using the Kotlin extensions, if not it would be `NavigationUI.setupWithNavController(toolbar, navController)`).

That should set up the up button for you, but it would likely also result in the bug I've described unless they have fixed that somehow in the latest navigation library version which I didn't have time to check yet.

**Comment by Dennis815** [comment]
@ubuntudroid No worries. Thank you for finding the time and looking at my code.

I do believe I am using the Kotlin extensions because I have declared the following dependencies in the build.gradle file:
```
    def nav_version = "1.0.0-alpha02"
    implementation "android.arch.navigation:navigation-fragment-ktx:$nav_version"
    implementation "android.arch.navigation:navigation-ui-ktx:$nav_version"
```
I am also importing the following in MainActivity.kt:
```
import androidx.navigation.NavController
import androidx.navigation.Navigation
import androidx.navigation.fragment.NavHostFragment
import androidx.navigation.ui.NavigationUI
import kotlinx.android.synthetic.main.activity_main.*
import kotlinx.android.synthetic.main.fragment_song_details_layout.*
```
However I am getting an error when making either of the suggested calls. For example:

```
        val navController = host.navController
        toolbar.setupWithNavController(navController) //or: NavigationUI.setupWithNavController(toolbar, navController)
```
I get an unresolved reference error on `setupWithNavController` with the former. With the latter (commented above) I get an error on the sale function call saying it can't be called with the toolbar argument supplied as it can only be called by passing a BottomNavigationView or NavigationView as the first argument.

I think the documentation could be clearer on this point (my emphasis):

> The Navigation Architecture Component includes a NavigationUI class. This class has several static methods you can use connect **menu items** with navigation destinations. For example, the following code shows how to use the setupWithNavController() method to connect items in the menu drawer to the NavigationView:

I am not familiar with NavigationView but I think it is used in the side navigation drawer.

This sample app for Navigation makes the following call instead:
```
setupActionBar(navController)
```
Perhaps this is the missing piece of the puzzle - as it is called in addition to `setupSupportActionBar(toolbar)` - however when I try to make the same call I get an unresolved reference error on `setupActionBar`.

I get the same results on alpha01 to 03. Alpha04 won't build for me though.

**Comment by ceruleanotter** [comment]
This was fixed in [alpha087](https://issuetracker.google.com/117333663). You can read about the new [AppBarConfiguration](https://developer.android.com/reference/androidx/navigation/ui/AppBarConfiguration) class in the [documentation](https://developer.android.com/topic/libraries/architecture/navigation/navigation-ui) and it will be added to the codelab shortly via #40
