### ISSUE TITLE
How to navigate the same level pages ?

### ISSUE THREAD

**Issue by gavinliu** [googlecodelabs/android-navigation#15]
![device-2018-05-31-131531](https://user-images.githubusercontent.com/3281741/40762840-ea1b76ec-64d4-11e8-9e69-0e6d95a71be8.png)

Like BottomNavigationView, Home & Deeplink are part of  the same level page, Deeplink should not have backstack. How to implement this feature?

**Comment by viperwarp** [comment]
I've posted a workaround over in https://github.com/googlecodelabs/android-navigation/issues/13#issuecomment-395256248

**Comment by ceruleanotter** [comment]
This was fixed in [alpha087](https://issuetracker.google.com/117333663). You can read about the new [AppBarConfiguration](https://developer.android.com/reference/androidx/navigation/ui/AppBarConfiguration) class in the [documentation](https://developer.android.com/topic/libraries/architecture/navigation/navigation-ui) and it will be added to the codelab shortly via #40
