### ISSUE TITLE
how to remove fragment from stack?

### ISSUE THREAD

**Issue by zhangbaogithub** [googlecodelabs/android-navigation#19]
I create a splash fragment, I hope when I go to home fragment, the splash fragment is removed, what should I do?

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask it on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
