### ISSUE TITLE
How do I set deepLink URI with different gradle product flavor?

### ISSUE THREAD

**Issue by b95505017** [googlecodelabs/android-navigation#25]
In old intent-filter way, we could setup different URI hosts through `manifestPlaceholders` for each product flavor easily, e.g. alpha/beta/production URI host. How to migrate into Navigation `<deepLink app:uri="{host}"/>` way?

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
