### ISSUE TITLE
id/action_plant_list_fragment_to_plant_detail_fragment is unknown to this NavController

### ISSUE THREAD

**Issue by Suman085** [googlecodelabs/android-navigation#26]
Having crash issues in navigation while frequently changing the fragments in and out. in android-sunflower applciation

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

I believe you're referring to the [Sunflower sample app](https://github.com/googlesamples/android-sunflower) - please post your [issue there](https://github.com/googlesamples/android-sunflower/issues) so that it can be resolved.
