### ISSUE TITLE
Please add the bundle on BottomNavigationView method (setupWithNavController) (Code In Description)

### ISSUE THREAD

**Issue by HamletLeon** [googlecodelabs/android-navigation#29]
I don't understand the reason why the NavigationUI doesn't admit a override on the onNavDestinationSelected or just a main bundle for all the view Like this:

`setupWithNavController(mBinding.navigation, mNavController, mArguments.toBundle())`
`onNavDestinationSelected(item, navController, false, args)`

And all fragments that are implemented in the BottomNavigationView can have those arguments.

I had to use all the legacy code of NavigationUI just to change this section from null to my Bundle arguments:

`fun onNavDestinationSelected(... , bundle: Bundle? = null){`
     `...`
     `navController.navigate(item.itemId, bundle, options)`
`}`

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab. This sounds like a feature request. Please open a bug/feature request on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
