### ISSUE TITLE
how to navigate to the third fragment and close current fragment at the same time?

### ISSUE THREAD

**Issue by 424385117** [googlecodelabs/android-navigation#39]
can you help me?

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
