### ISSUE TITLE
Navigation Drawer / icon in portrait mode ?

### ISSUE THREAD

**Issue by ajonno** [googlecodelabs/android-navigation#42]
as stated on another ticket here: "...You also just will see the drawer when e.g. entering split screen mode or rotate to landscape."

can you please clarify how we can show the drawer menu when in portrait mode ? i think it would be great if this can be added to the tutorial (which is fantastic).

**Comment by Daemon-Devarshi** [comment]
@ajonno I think it is purposefully left for the reader as an exercise and clue is somewhere in the provided code itself ;)

So if we analyse the sample code provided by Google we can find that there are 3 versions of navigation_activity.xml:

1. navigation_activity.xml
2. navigation_activity.xml (h470dp)
3. navigation_activity.xml (w960dp)

Few related points to consider:

- The first one is inflated when app is in split screen mode. The second one is inflated when app is in normal portrait mode.
- The first layout is enclosed within androidx.drawerlayout.widget.DrawerLayout tag. The second layout is enclosed within LinearLayout tag.
- The first contains com.google.android.material.navigation.NavigationView tag. The second layout does not contain this tag.

Do you need more clues? :P

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

The layout navigation_activity.xml (h470dp) will be used on phones in portrait mode as @Daemon-Devarshi mentioned. This layout does not include the navigation drawer and instead includes the bottom navigation, which is why you should open the app in split screen to see the navigation drawer. The reason there is not a layout with both a navigation drawer and bottom navigation is because [Material Design guidelines cautions against this](https://material.io/design/components/navigation-drawer.html#u).

I'm adding this information to step 9, since I can understand why it's confusing. If you were to remove navigation_activity.xml (h470dp) and navigation_activity.xml (w960dp), you'd see the drawer in portrait mode.
