### ISSUE TITLE
FlowStepFragmentDirections is not generating static methods for passing safe args

### ISSUE THREAD

**Issue by vicgithb** [googlecodelabs/android-navigation#48]
As per the documentation, Directions classes are generated for every distinct destination with actions.

Now consider a scenario:
- 
Suppose, There are three fragments FragA(with no argument),  FragB( with one argument), FragC(with two argument).

In the navigation graph, create two instances of Frag A , single instance of Frag B , single instance of Frag C. 

From first instance of Frag A create an action named "action_next" to Frag B.
From second instance of Frag A create an action named "action_next" to FragC.

**Build the project and it will generate Direction class for Frag A. Only, single "ActionNext" method is getting generated instead of two.** 

Since there is only one "ActionNext" method so it should behave as per the context in which it is being used; but it appears that static code of direction class is not handling it right now.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
