### ISSUE TITLE
Step8: Type mismatch with generated FlowStepArgument class

### ISSUE THREAD

**Issue by alvindizon** [googlecodelabs/android-navigation#49]
On Step 8, the code 
`val safeArgs = FlowStepFragmentArgs.fromBundle(arguments)` 

produces a `type mismatch error: inferred type is Bundle? but Bundle was expected`

**Comment by sigmaprojects** [comment]
Ran into this as well.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

This had to do with breaking changes in one of the alpha releases that came out after the last publishing of the codelab code. I'm pushing an update to the codelab soon that will fix this -- sorry for the confusion. The proper way to get args in Kotlin is now:

`val safeArgs: FlowStepFragmentArgs by navArgs()`

**Comment by edh08001** [comment]
@ceruleanotter Just as a heads up, your Udacity course still uses the old method which throws this type mismatch error. While I was fortunately able to find this post eventually, it was a bit of a pain having an officially supported tutorial giving you broken, outdated methods. I am only about 50% through the "App Navigation" tutorial, specifically on module 19: "Adding Safe Arguments". That would mean if this one single thread didn't exist, or if I never found it, it'd make the entire back half of the course unusable since they build on each previous lesson. 

I know it's probably not feasible to update the video portion of the lessons, but a quick disclaimer/update to the text portion of the course outlining any changes would help quite a lot.
