### ISSUE TITLE
Why Recreate Fragment when bottomNavigationView.onNavigationItemSelected ?

### ISSUE THREAD

**Issue by gavinliu** [googlecodelabs/android-navigation#53]
I click on bottomNavigationView From DeeplinkFragment to HomeFragment, Discovery will recreate HomeFragment. 

Why ? It is a feature or bug ?

```
2019-01-31 18:08:31.500 29778-29778/com.example.android.codelabs.navigation D/Test: onCreate
2019-01-31 18:08:34.453 29778-29778/com.example.android.codelabs.navigation D/Test: onCreate
```

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

This is how the library was originally designed, but we've gotten a *lot* of feedback so providing alternate behavior is on our radar. You can follow and comment on the feature request for multiple backstacks [here](https://issuetracker.google.com/issues/80029773)

There is also an advanced navigation sample that shows how to get the multiple backstack behavior that you can check out [here](https://github.com/googlesamples/android-architecture-components/tree/master/NavigationAdvancedSample).

I'm closing this issue because this forum is for issues with the codelab.

**Comment by gurpreet433** [comment]
Hi, its been 2 years we are still stuck with workarounds ? is navigations component dead or we might get an update in future?

**Comment by Svilcata19** [comment]
Why is this closed when it's still a thing? Is it dead?
