### ISSUE TITLE
Step 5, createNavClickListener in clickListener

### ISSUE THREAD

**Issue by gordinmitya** [googlecodelabs/android-navigation#58]
at the bottom of the page
```kotlin
val button = view.findViewById<Button>(R.id.navigate_destination_button)
button?.setOnClickListener(
        Navigation.createNavigateOnClickListener(R.id.flow_step_one_dest, null)
)
```
calling createNavigateOnClickListener in onClickListener isn't equal to previous example with 
``` kotlin
val button = view.findViewById<Button>(R.id.navigate_destination_button)
button?.setOnClickListener(
        findNavController().navigate(R.id.flow_step_one_dest)
)
```
should be like
```kotlin
Navigation.createNavigateOnClickListener(R.id.flow_step_one_dest, null)
```

another point is that `setOnClickListener` should be with curly braces `{ }`

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I added the explicit `null` for the argument bundle so that the two would match. You shouldn't need to curly braces since the `createNavigateOnClickListener` method creates the lambda - [see the docs for this](https://developer.android.com/guide/navigation/navigation-getting-started#navigate_to_a_destination).

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
