### ISSUE TITLE
delete .idea folder

### ISSUE THREAD

**Issue by mercuriete** [googlecodelabs/android-navigation#65]
1) .idea folder should be in .gitignore
2) .idea folder shoudn't be in git.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

Normally yes, but in this case the .idea folder just contains the navEditor.xml which should give positioning data for elements in the navgraph so that the navgraph looks more organized when opened. If this is causing issues or is not the case, please re-open this issue.

**Comment by mercuriete** [comment]
@ceruleanotter 
Thanks, now I understand.
