### ISSUE TITLE
How can i add fragment on Navigation controller (Navigation component) Instead of replace?  I tried to navigate fragment according to android architecture but i am not possible to understand how i add or replace fragment as our previous architecture.  example: if i move A fragment to B fragment and when i press back from B fragment then A fragment always gets reload. Suggest me any one if i do add fragment 

### ISSUE THREAD

**Issue by chiragsharma991** [googlecodelabs/android-navigation#70]

**Comment by StevenWT** [comment]
I had the same question!

**Comment by StevenWT** [comment]
I want to save fragments state. Fragments according to official used the replace() method that doesn't save fragment state, but we expect to use the add()/hide() methods shows fragments to save fragment state. My solution is to not use the official implementation implementation "androidx.navigation:navigation-fragment:$nav_version", directly put the library's code in your project, and then modify the replace() method to hide()/add() method.

* androidx.navigation.fragment.FragmentNavigator.java

```
public NavDestination navigate(@NonNull Destination destination, @Nullable Bundle args,
            @Nullable NavOptions navOptions, @Nullable Navigator.Extras navigatorExtras) {
        
//      ft.replace(mContainerId, frag);

//      change to  

        if(mFragmentManager.getFragments().size()>0){
            ft.hide(mFragmentManager.getFragments().get(mFragmentManager.getFragments().size()-1));
            ft.add(mContainerId, frag);
        }else {
            ft.replace(mContainerId, frag);
        }
        
}
```
I have a demo you can run.
[fragment-demo](https://github.com/StevenWT/fragment-demo)

**Comment by utkukutlu** [comment]
You can use this solution
~~https://stackoverflow.com/questions/58674495/android-navigation-component-add-instead-of-replace~~

https://stackoverflow.com/a/59531175/9167575

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

This might be referring to https://issuetracker.google.com/issues/80029773 - it's a feature request the team is working on.

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.

**Comment by ramakrishnajoshi** [comment]
@chiragsharma991 @StevenWT 

Jetpack Navigation Component supports replacing fragments as of now.
 
**There is no support for adding fragments**. 

Workaround to retain api data in fragment when back button is pressed is to either save the data (Fragment viewstate) in a ViewModel and make a check in onViewCreated() or to use Full Screen DialogFragments. For dialog fragment check this https://gist.github.com/utkukutlu/bd2e37253e7184179d923321e3ea72c1

**Comment by qq2748** [comment]
if you  use add() and hide()  the fragment onPause()  and onStop() will not called,   when the backPress() call , onStart() and onResume() will not called too.
