### ISSUE TITLE
Chrome browser does not open app with link www.example.com/urlTest

### ISSUE THREAD

**Issue by tmvo41** [googlecodelabs/android-navigation#76]
Tried the url on Step 11. Does not bring the option to open the app. It only open up a link to www.example.com on the browser. The ADB method works, though.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab. Note that this step is a bit tricky (hence a lot of extra screenshots). The "Google app" is what opens when you use the home-screen search bar -- it's easily confused with Chrome, which will not result in the correct behavior.

If you are still experiencing this issue, please re-open and let me know what device you're on and include screenshots of which app you're using.
