### ISSUE TITLE
Is it possible to programmatically create "Implicit" deep links? 

### ISSUE THREAD

**Issue by wahibhaq** [googlecodelabs/android-navigation#77]
I have researched a lot and explored API as well but just can't make it work. The situation, I have is that we have dynamic **schemes** so I can't make it hardcoded in the graph xml. 

Is it possible to programmatically define those implicit deep links for each destination? 

I know it is easy to do so for explicit ones. Also, noticed that [addDeeplink(String uriPattern)](https://developer.android.com/reference/androidx/navigation/NavDestination.html#addDeepLink(java.lang.String)) was added in latest alpha version. Is it something that can be used? 

A sample code could be very helpful especially using nav controller and destination.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab. I see you also reported in the [issue tracker ](https://issuetracker.google.com/issues/140712637) - that is the correct place to give this kind of feedback. If you didn't see, this was marked as a dup of https://issuetracker.google.com/issues/110237825
