### ISSUE TITLE
Navigation component seems just working with short dynamic link (firebase)

### ISSUE THREAD

**Issue by rafaelaguerra** [googlecodelabs/android-navigation#78]
Navigation component seems just working with short dynamic link

Example:
**Long Dynamic Link**
https://domaindebug.page.link/?link=https://www.domain.com&apn=com.x.debug&isi=122...6&ibi=com.ios.x.debug&efr=1

**Short Dynamic Link**
https://domaindebug.page.link/register 

```
<fragment
        android:id="@+id/fragment_register"
        android:name="com.x.presentation.feature.identification.view.RegisterFragment"
        tools:layout="@layout/fragment_register">
        <action
            ... />
        <argument
            android:name="code"
            android:defaultValue="@null"
            app:argType="string"
            app:nullable="true" />
        <deepLink
            android:id="@+id/deepLink"
            app:uri="https://domaindebug.page.link/register?code={code}" />
</fragment>
```

How can I manage this? I also can't find any documentation about integrate firebase dynamic deeplink + navigation component

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
