### ISSUE TITLE
Error: illegal character: '\u0000'

### ISSUE THREAD

**Issue by daimonkor** [googlecodelabs/android-navigation#9]
Please fix bug with stubs http://prntscr.com/jgrbso http://prntscr.com/jgrc7i http://prntscr.com/jgrdge x64. Thanks for help.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab.

If you have questions about how to do something outside of the codelab scope with Navigation, you can ask them on Stack Overflow using the [Stack Overflow Navigation tag](https://stackoverflow.com/questions/tagged/android-navigation-component).

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
